.386
.MODEL FLAT, STDCALL
OPTION CASEMAP: NONE
INCLUDE C:\MASM32\INCLUDE\WINDOWS.INC
INCLUDE C:\MASM32\INCLUDE\KERNEL32.INC
INCLUDE C:\MASM32\INCLUDE\USER32.INC
INCLUDELIB C:\MASM32\LIB\USER32.LIB
INCLUDELIB C:\MASM32\LIB\KERNEL32.LIB


.DATA
Sstr DB 13, 10, "Strings", 0
	p DB 5
	k DW 500
	s DD 5000
	ten DT 88.38
.CODE
START:
	XOR EAX, EAX
	MOV AX, k
	MOV BX, WORD PTR [p]
	MUL BX
	MOV k, AX
	push NULL
  	call ExitProcess
END START
