.386
.MODEL FLAT, STDCALL
OPTION CASEMAP: NONE
INCLUDE C:\MASM32\INCLUDE\WINDOWS.INC
INCLUDE C:\MASM32\INCLUDE\KERNEL32.INC
INCLUDE C:\MASM32\INCLUDE\USER32.INC
INCLUDELIB C:\MASM32\LIB\USER32.LIB
INCLUDELIB C:\MASM32\LIB\KERNEL32.LIB


.DATA
	p DW 5
	k DW 500
	s DD 5000
.CODE
START:
	XOR EAX, EAX
	XOR EBX, EBX
	XOR ECX, ECX
	XOR EDX, EDX
	MOV EAX, s
	MOV BX, k
	DIV BX
	MOV CX, p
	SUB AX, CX
	push NULL
	call ExitProcess
END START
