.386
.MODEL FLAT, STDCALL
OPTION CASEMAP: NONE
INCLUDE C:\MASM32\INCLUDE\WINDOWS.INC
INCLUDE C:\MASM32\INCLUDE\KERNEL32.INC
INCLUDE C:\MASM32\INCLUDE\USER32.INC
INCLUDELIB C:\MASM32\LIB\USER32.LIB
INCLUDELIB C:\MASM32\LIB\KERNEL32.LIB
.DATA
	i DW 10
	j DW -5
	k DW 3
.CODE
START:
	; i^3 + j^3 - k^3 + 10^7/i 

	MOVSX EAX, i
	MOV EBX, EAX; Второй множитель
	IMUL EBX, EAX
	IMUL EBX, EAX
	

	MOVSX EAX, j
	MOV EDX, EAX
	IMUL EDX, EAX
	IMUL EDX, EAX; j^3

	ADD EBX, EDX; i^3+j^3
	
	MOVSX EAX, k
	MOV ECX, EAX
	IMUL ECX, EAX
	IMUL ECX, EAX; k^3

	SUB EBX, ECX; i^3+j^3-k^3

	MOVSX EAX, i
	MOV ECX, EAX
	MOV EAX, 10*10*10*10*10*10*10
	XOR EDX, EDX
	IDIV ECX

	ADD EBX, EAX

	push NULL
  	call ExitProcess
END START
