.386 
.MODEL FLAT, STDCALL 
OPTION CASEMAP: NONE 
INCLUDE C:\MASM32\INCLUDE\WINDOWS.INC 
INCLUDE C:\MASM32\INCLUDE\KERNEL32.INC 
INCLUDE C:\MASM32\INCLUDE\USER32.INC 
INCLUDELIB C:\MASM32\LIB\USER32.LIB 
INCLUDELIB C:\MASM32\LIB\KERNEL32.LIB 
.DATA	
	a dq 123456789
	b dq -22
	r db 16 dup(?)
.CODE 
START:
	MOV EAX, DWORD PTR a[0]
	MUL DWORD PTR b[0]; a0 * b0
	MOV DWORD PTR r[0], EAX; c0
	MOV DWORD PTR r[4], EDX; c1 во второе дв. слово
	
	MOV EAX, DWORD PTR a[4]; a1
	MUL DWORD PTR b[0]; a1 * b0
	ADD DWORD PTR r[4], EAX; c1 + d0
	ADC DWORD PTR r[8], EDX; d1
	ADC DWORD PTR r[12], 0; перенесенная 1, если была

	MOV EAX, DWORD PTR a[0]; a0
	MUL DWORD PTR b[4]; a0 * b1
	ADD DWORD PTR r[4], EAX; c1 + d0 + e0
	ADC DWORD PTR r[8], EDX; d1 + e1
	ADC DWORD PTR r[12], 0; перенесенная 1, если была

	MOV EAX, DWORD PTR a[4]; a1
	MUL DWORD PTR b[4]; b1
	ADD DWORD PTR r[8], EAX; d1 + e1 + f0
	ADC DWORD PTR r[12], EDX; f1
	
	push NULL 
	call ExitProcess 
END START 