# Generated by Django 3.1.4 on 2020-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20201228_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepostpiece',
            name='postpiece_ptr',
        ),
        migrations.RemoveField(
            model_name='textpostpiece',
            name='postpiece_ptr',
        ),
        migrations.AddField(
            model_name='postpiece',
            name='code_data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postpiece',
            name='image_data',
            field=models.ImageField(null=True, upload_to='posts_images'),
        ),
        migrations.AddField(
            model_name='postpiece',
            name='text_data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='CodePostPiece',
        ),
        migrations.DeleteModel(
            name='ImagePostPiece',
        ),
        migrations.DeleteModel(
            name='TextPostPiece',
        ),
    ]
