.386 
.MODEL FLAT, STDCALL 
OPTION CASEMAP: NONE 
INCLUDE C:\MASM32\INCLUDE\WINDOWS.INC 
INCLUDE C:\MASM32\INCLUDE\KERNEL32.INC 
INCLUDE C:\MASM32\INCLUDE\USER32.INC 
INCLUDELIB C:\MASM32\LIB\USER32.LIB 
INCLUDELIB C:\MASM32\LIB\KERNEL32.LIB 
.DATA	
	a dq 0FFFFFFFFFFFFFFFh
	b dq 0FFFFFFFFFFFFFFFh
	r db 16 dup(?)
.CODE 
START:
	MOV EAX, DWORD PTR a[0]

	MUL EAX, DWORD PTR [b]; a0 * b0
	MOV DWORD PTR r[0], DWORD PTR EAX ; c0 сохранили
	MOV DWORD PTR r[4], EDX; 	

	MOV EBP, EDX; с1 для вычисления
	MOV EAX, DWORD PTR [a]; a0
	IMUL EAX, DWORD PTR [b+4]; b1 * a0
	
	ADC EBP, EAX; c1 + d0
	MOV EBX, EDX; d1 для дальнейших вычислений
	
	MOV EAX, DWORD PTR [b+4]; b1
	MUL EAX, DWORD PTR [a]; b1 * a0 = d1:d0
	ADC EBP, EAX; c1 + d0 + e0
	
	MOV DWORD PTR r[4], DWORD PTR EBP; c1 + d0 + e0 сохранили
	
	MOV EBX, EBP; d1
	ADC EBP, EDX; e1
	
	MOV EAX, DWORD PTR [a+4]; a1
	MUL EAX, DWORD PTR [b+4]; a1 * b1
	
	ADC EBP, EAX; d1 + e1 + f0
	MOV DWORD PTR r[8], DWORD PTR EBP; d1 + e1 + f0 сохранили
	
	MOV DWORD PTR r[12], DWORD PTR EDX; f1 сохранили	
	
	push NULL 
	call ExitProcess 
END START 